INSERT INTO ROLES (ID, NAME) VALUES (1, 'ADMIN');
INSERT INTO ROLES (ID, NAME) VALUES (2, 'USER');
INSERT INTO USERS (ID, EMAIL, PASSWORD) VALUES (1, 'admin@zooplus.com', 'pwd12345');
INSERT INTO USERROLES (USER_ID, ROLE_ID) VALUES (1, 1);
INSERT INTO USERROLES (USER_ID, ROLE_ID) VALUES (1, 2);
