DROP TABLE IF EXISTS PERSONS;
DROP SCHEMA IF EXISTS OPENEXCHANGE;
CREATE SCHEMA OPENEXCHANGE AUTHORIZATION DBA;
SET SCHEMA OPENEXCHANGE;
CREATE MEMORY TABLE OPENEXCHANGE.PERSONS(ID INTEGER,NAME VARCHAR(200), PASSWORD VARCHAR(200));