DROP TABLE IF EXISTS USERS;
CREATE MEMORY TABLE USERS (
	ID BIGINT PRIMARY KEY AUTO_INCREMENT,
	EMAIL VARCHAR(200) UNIQUE NOT NULL,
	PASSWORD VARCHAR(200) UNIQUE NOT NULL,
	CREATEDAT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	ENABLED BOOLEAN DEFAULT TRUE
);