DROP TABLE IF EXISTS USERS;
DROP SCHEMA IF EXISTS OPENEXCHANGE;
CREATE SCHEMA OPENEXCHANGE AUTHORIZATION SA;
SET SCHEMA OPENEXCHANGE;
CREATE MEMORY TABLE OPENEXCHANGE.USERS  (
	ID BIGINT AUTO_INCREMENT PRIMARY KEY,
	EMAIL VARCHAR(200) UNIQUE NOT NULL,
	PASSWORD VARCHAR(200) UNIQUE NOT NULL
);