DROP TABLE IF EXISTS SUBSCRIBERS;
DROP SCHEMA IF EXISTS OPENEXCHANGE;
CREATE SCHEMA OPENEXCHANGE AUTHORIZATION SA;
SET SCHEMA OPENEXCHANGE;
CREATE MEMORY TABLE OPENEXCHANGE.SUBSCRIBERS  (
	ID BIGINT AUTO_INCREMENT PRIMARY KEY,
	EMAIL VARCHAR(200) UNIQUE NOT NULL,
	PASSWORD VARCHAR(200) UNIQUE NOT NULL
);