spring:
  jpa:
    show_sql: false
    hibernate:
      ddl-auto: none
  datasource:
    platform: mysql
  eureka:
    client:
      serviceUrl:
        defaultZone: http://localhost:8761/eureka/


